name: warcrafty
description: A high-performance Dart library for reading and writing World of Warcraft DBC files.
version: 1.0.1
repository: https://github.com/calsranna/warcrafty
homepage: https://github.com/calsranna/warcrafty
issue_tracker: https://github.com/calsranna/warcrafty/issues

environment:
  sdk: ^3.10.0

dependencies:
  # path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
